- hosts: localhost
  gather_facts: yes
  tasks:
  - include_role:
      name: "uperf-bench"
    when: uperf is defined and uperf.pair > 0
  - include_role:
      name: "fio-bench"
    when: fio is defined and fio.clients > 0
